### ISSUE TITLE
Have you heard of Sandboxie?

### ISSUE THREAD

**Issue by gabefair** [dblohm7/sandbox-win32#1]
Hello I came across this while looking for sandbox methods that work with windows on ARM. 
How does your sandbox methods differ from Sandboxie? https://github.com/sandboxie-plus/Sandboxie

**Comment by dblohm7** [comment]
I wrote this in 2013 when I was working at Mozilla and serving on an ad-hoc committee tasked with evaluating sandboxing options for EME, and eventually, web content.

As the Readme states, this is a testbed for various sandboxing techniques, as well as testing the behaviour of code within the sandbox.

So yes, I am well aware of Sandboxie, the Chromium sandbox, et al. But implementing a production sandbox was never the intent of this repo.
